### ISSUE TITLE
ShowAll Querystring parameter support

### ISSUE THREAD

**Issue by Swimburger** [DNNCommunity/DNN.Blog#140]
How do I respond to `?showall=true` querystring parameter, to show all blog posts instead of paginated?
Is there a way to grab that querystring value inside of the Blog Template Engine?

**Comment by valadas** [comment]
One way to do this would be to have one page (lets call it /Blog ) that shows paging, copy the module on another page (lets call it /Blog-all and set the options to show the content of the existing blog, then on that page, set the pager number high enough so that there is no pager shown.

Then on the first page, you can put a button to show all that simply points to the other page.

**Comment by Swimburger** [comment]
We'll only want to have /Blog show up in Google, not /Blog-all so that wouldn't work that well for us.

**Comment by EPTamminga** [comment]
You can set the indexing page option for the  blog page to NO.
